### ISSUE TITLE
Getting Error while running this code

### ISSUE THREAD

**Issue by git-dev-mean** [regulaforensics/FaceSDK-web-js-client#16]
(node:2325) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/mnt/d/OCR/Regula/FaceSDK-web-js-client-master/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/mnt/d/OCR/Regula/FaceSDK-web-js-client-master/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/mnt/d/OCR/Regula/FaceSDK-web-js-client-master/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2325) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hleb-albau** [comment]
Hello, could you clarify a bit what steps or code caused this error?

**Comment by git-dev-mean** [comment]
hi, I have installed FaceSDK CPU version and installed the license as well and then downloaded this repo and run following commands
1. npm install 
2. npm run build
3. cd example
4. npm install
5. node .

Then issue occured on following line of code

const sdk = new FaceSdk({basePath: "http://localhost:41101"})

const response = await sdk.matchingApi.match({
    images: [
        {type: ImageSource.LIVE, data: face1, index: 1},
        {type: ImageSource.DOCUMENT_RFID, data: face2, index: 2}
    ]
  })

If I add catch statement then I receive response as undefined

**Comment by hleb-albau** [comment]
Yeah, we already update examples to the 3.0 FaceSDK version, which  I hope to release this week. Thus, the example uses a new endpoint introduced in 3.0.

Try to use the example from 2.1 version https://github.com/regulaforensics/FaceSDK-web-js-client/tree/3198df11ec50ffc4fa577c680d2005bcd17e5e77/example
